function [fitresult, gof] = createFit(fitdataX, fitdataY)
%CREATEFIT(FITDATAX,FITDATAY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fitdataX
%      Y Output: fitdataY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jun-2021 15:26:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fitdataX, fitdataY );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.946288016153119;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fitdataY vs. fitdataX', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'fitdataX', 'Interpreter', 'none' );
ylabel( 'fitdataY', 'Interpreter', 'none' );
grid on


fitdataX = [0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100];
fitdataY = [0 1.0933 2.3401 3.6788 5.0888 6.5778 8.1240 9.7213 11.3517 13.0426 14.7526 16.4875 18.2397 20.0056 21.7758 23.5477 25.3002 27.0686 28.8125 30.5369 32.2235]