function [fitresult, gof] = createFit(fitdataY, fitdataX)
%CREATEFIT(FITDATAY,FITDATAX)
%  Create a fit.
%
%  Data for 'Linearity Fitted Model' fit:
%      X Input : fitdataY
%      Y Output: fitdataX
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jun-2021 15:35:44


%% Fit: 'Linearity Fitted Model'.
[xData, yData] = prepareCurveData( fitdataY, fitdataX );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999999844331357;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Linearity Fitted Model' );
h = plot( fitresult, xData, yData );
legend( h, 'fitdataX vs. fitdataY', 'Linearity Fitted Model', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'fitdataY', 'Interpreter', 'none' );
ylabel( 'fitdataX', 'Interpreter', 'none' );
grid on


